name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: prepare
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - name: Typings
        run: yarn types
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info
